import{a as p,S as m,i as u}from"./assets/vendor-mdVVRe9K.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const y="32552782-0d4c86680018457e820f20492";p.defaults.baseURL="https://pixabay.com/api/";const h=async e=>{const t={key:y,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true"};try{return(await p.get("",{params:t})).data}catch(a){throw new Error(a.response?a.response.status:"Unknown Error")}},g=e=>`<li class="gallery-card">
    <a href="${e.largeImageURL}">
      <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img" />
    </a>
    <div class="gallery-info">
      <p><span class="label">Likes</span> <span class="value">${e.likes}</span></p>
      <p><span class="label">Views</span> <span class="value">${e.views}</span></p>
      <p><span class="label">Comments</span> <span class="value">${e.comments}</span></p>
      <p><span class="label">Downloads</span> <span class="value">${e.downloads}</span></p>
    </div>
  </li>`,f=e=>{const t=document.querySelector(".js-gallery");t.innerHTML=e.map(g).join(""),b.refresh()},L=e=>{u.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})},i=e=>{u.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})},b=new m(".gallery-card a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),d=document.querySelector(".js-search-form"),l=document.querySelector(".js-gallery"),c=document.querySelector(".loader"),w=async e=>{e.preventDefault();const t=d.elements.text.value.trim();if(!t){L();return}c.classList.remove("hidden");try{const a=await h(t);if(a.hits.length===0){i("Sorry, there are no images matching your search query. Please try again!"),l.innerHTML="";return}l.innerHTML="",f(a.hits)}catch{i()}finally{c.classList.add("hidden")}};d.addEventListener("submit",w);
//# sourceMappingURL=index.js.map
